gives many things proper recipes, and other fixes
Operation-Eclipse/red-eclipse-14 pull request #24
Opened 2023-08-28 22:43 UTC by terezi4real

## About the PR

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

2023-08-31 00:27 UTC, terezi4real commented
i fucked somethin up

2023-09-01 13:09 UTC, sTiKyt requested changes
Changelog request:

- [ ] Specify the items that were removed.
- [ ] Specify the items that were added.
- [ ] Specify the items that now have a proper recipe.
- [ ] Specify the items that are now crafted in a different machine.


That's it for now. I will review further after this is resolved.

2023-09-01 13:09 UTC, sTiKyt commented on Resources/Prototypes/Research/arsenal.yml
Why are you commenting out researches?

2023-09-01 13:09 UTC, sTiKyt commented on Resources/Prototypes/Research/disciplines.yml
Same question here

2023-09-01 13:09 UTC, sTiKyt commented on Resources/Prototypes/_RedEclipse/Entities/Objects/Factory/Structures/Assemblers/FactoryClownAssembler.yml
Dynamic recipes are the ones unlocked through research?

2023-09-01 13:09 UTC, sTiKyt commented on Resources/Prototypes/_RedEclipse/Recipes/Factory/Assemblers/assembler_medical.yml
> -  completetime: 1
Well, if you remove FactorySyndicateSmokesPacket proper commit would be "Removed FactorySyndicateSmokesPacket recipe", bro, it's impossible to figure all this out properly fast when proper commits or changelog are non-existent

2023-10-03 09:20 UTC, closed without merging